name: Build, Compile, and Release Rust Program

on:
  push:
    branches: [ main, develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Compile-Linux
        id: compile-linux
        run: |
          cargo build --release
          tar -czf jikken-x86_64-linux.tar.gz -C target/release jk
          mkdir -p upload-linux && cp "jikken-x86_64-linux.tar.gz" upload-linux/

      - name: Attach compressed file to release
        uses: actions/upload-artifact@main
        with:
          name: upload-linux
          path: upload-linux

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Compile-macOS
        id: compile-mac
        run: |
          cargo build --release
          tar -czf jikken-x86_64-apple-darwin.tar.gz -C target/release jk
          mkdir -p upload-mac && cp "jikken-x86_64-apple-darwin.tar.gz" upload-mac/

      - name: Attach compressed file to release
        uses: actions/upload-artifact@main
        with:
          name: upload-mac
          path: upload-mac

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Compile-Windows
        id: compile-windows
        run: |
          cargo build --release

      - name: Compress file
        shell: powershell
        run: |
          Compress-Archive -Path target/release/jk.exe -DestinationPath jk.zip
          mkdir upload-windows
          Move-Item jk.zip upload-windows
          Move-Item jk.exe upload-windows

      - name: Attach compressed file to release
        uses: actions/upload-artifact@main
        with:
          name: upload-windows
          path: upload-windows

  release:
    needs: [ build-linux, build-mac, build-windows ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@main
        name: Download Linux
        with:
          name: upload-linux

      - uses: actions/download-artifact@main
        name: Download Mac
        with:
          name: upload-mac

      - uses: actions/download-artifact@main
        name: Download Windows
        with:
          name: upload-windows
          
      - name: Get SHA256 Values
        run: |
          mkdir jk_linux jk_mac jk_windows
          sha256sum jikken-x86_64-linux.tar.gz | awk '{print $1}' > linux_zip_hash.txt
          sha256sum jikken-x86_64-apple-darwin.tar.gz | awk '{print $1}' > mac_zip_hash.txt
          sha256sum jk.zip | awk '{print $1}' > windows_zip_hash.txt
          tar -xf jikken-x86_64-linux.tar.gz -C jk_linux
          tar -xf jikken-x86_64-apple-darwin.tar.gz -C jk_mac
          sha256sum jk_linux/jk | awk '{print $1}' > linux_exe_hash.txt
          sha256sum jk_mac/jk | awk '{print $1}' > mac_exe_hash.txt
          sha256sum jk_windows/jk.exe | awk '{print $1}' > windows_exe_hash.txt
          echo "LINUX_EXE_HASH=$(cat linux_exe_hash.txt)" >> "$GITHUB_ENV" 
          echo "LINUX_ZIP_HASH=$(cat linux_zip_hash.txt)" >> "$GITHUB_ENV"
          echo "MAC_EXE_HASH=$(cat mac_exe_hash.txt)" >> "$GITHUB_ENV"      
          echo "MAC_ZIP_HASH=$(cat mac_zip_hash.txt)" >> "$GITHUB_ENV"
          echo "WINDOWS_EXE_HASH=$(cat windows_exe_hash.txt)" >> "$GITHUB_ENV"      
          echo "WINDOWS_ZIP_HASH=$(cat windows_zip_hash.txt)" >> "$GITHUB_ENV"
          mv jk_windows/jk.exe jk_windows/jikken-windows.exe
          mv jk_windows/jk.zip jk_windows/jikken-windows.zip

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: james-jikkenio,louis-jikkenio

      - name: Release Type
        run: |
          if [[ ${{ github.ref }} == refs/heads/main ]]; then
            echo "PRERELEASE=false" >> "$GITHUB_ENV"
          else
            echo "PRERELEASE=true" >> "$GITHUB_ENV"
          fi

      - name: Create Release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}  # Access token for creating releases
        with:
          tag_name: v1.3.9  # Replace with your desired version tag
          release_name: Release v1.3.9  # Replace with your desired release name
          body: |
            **Release Notes**
            Docs can be found at: jikken.io
            Check the CHANGELOG.md for details.

            SHA-256 Binary Hashes
            - Windows (jk.exe): ${{ env.WINDOWS_EXE_HASH }}
            - Linux (jk): ${{ env.LINUX_EXE_HASH }}
            - Mac (jk): ${{ env.MAC_EXE_HASH }}

            SHA-256 Binary Hashes of compressed files.              
            - Windows (jikken-windows.zip) ${{ env.WINDOWS_ZIP_HASH }}
            - Windows (jikken-windows.exe) ${{ env.WINDOWS_EXE_HASH }}
            - Linux (jikken-x86_64-linux.tar.gz) ${{ env.LINUX_ZIP_HASH }}
            - Mac (jikken-x86_64-apple-darwin.tar.gz) ${{ env.MAC_ZIP_HASH }}

          draft: false
          prerelease: ${{ env.PRERELEASE }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: Upload Artifacts to Release
          path: |
            jikken-x86_64-linux.tar.gz
            jikken-x86_64-apple-darwin.tar.gz
            jikken-windows.zip
            jikken-windows.exe


      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
      #     limit-access-to-actor: true
      #     ## limits ssh access and adds the ssh public keys of the listed GitHub users
      #     limit-access-to-users: james-jikkenio,louis-jikkenio