name: Build, Compile, and Release Rust Program

on:
  push:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Compile-Linux-musl
        id: compile-linux-musl
        uses: gmiam/rust-musl-action@master
        with:
          args: cargo build --target x86_64-unknown-linux-musl --release
        
      - name: Compile-linux
        id: compile-linux
        run: |
          tar -czf jikken-x86_64-linux.tar.gz -C target/x86_64-unknown-linux-musl/release/ jk
          mkdir -p upload-linux && cp "jikken-x86_64-linux.tar.gz" upload-linux/

      - name: Attach compressed file to release
        uses: actions/upload-artifact@main
        with:
          name: upload-linux
          path: upload-linux
